# -*- coding: utf-8 -*-
""".tif to .jpg .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvmoEnpqqkl5FbqYzdbRfWf8SdHybaVR
"""

import glob, os, sys
from PIL import Image

folder =  source # Example: '/content/drive/MyDrive/Thesis_Paper/CNN/train/Pathogenic/'


for filepath in glob.iglob(os.path.join(folder, '*.tif')):
    image = Image.open(filepath).convert('RGB').convert('RGB')
    new_filepath = os.path.splitext(filepath)[0] + '.jpg'
    image.save(new_filepath)